version: '3.8'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8085
    ports:
      - 8085:8085
    volumes:
      - /media/qbittorrent/config:/config
      - /data/torrents/:/data/torrents
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    ports:
      - 7777:7777
      - 8080:8080
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /media/sabnzbd:/config
      - /data/usenet/complete:/data/usenet/complete
      - /data/usenet/incomplete:/data/usenet/incomplete
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /data/bazarr/config:/config
      - /data/:/data
    ports:
      - 6767:6767
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /data/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /data/radarr/config:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /data/sonarr/config:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /media/nginx:/data
      - /data/nginx/letsencrypt:/etc/letsencrypt